In [3]:
import numpy as np

In [5]:
a=np.arange(9)
print("the original array : \n",a)

the original array : 
 [0 1 2 3 4 5 6 7 8]


In [8]:
b=a.reshape(3,3)
print("the modified array : \n",b)

the modified array : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [12]:
print(b.flatten(order='f'))

[0 3 6 1 4 7 2 5 8]


In [15]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
print(np.transpose(a))

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [17]:
b=np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
c=b.reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
np.rollaxis(c,1,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
np.swapaxes(c,1,2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [31]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
b=np.array([10,11,12])
b

array([10, 11, 12])

In [33]:
np.add(a,b)

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20]])

In [35]:
np.subtract(a,b)

array([[-10, -10, -10],
       [ -7,  -7,  -7],
       [ -4,  -4,  -4]])

In [36]:
np.divide(a,b)

array([[0.        , 0.09090909, 0.16666667],
       [0.3       , 0.36363636, 0.41666667],
       [0.6       , 0.63636364, 0.66666667]])